server.port=8083
spring.application.name=pagerank-service

spring.data.redis.host=redis
spring.data.redis.port=6379

spring.kafka.bootstrap-servers=kafka-searchengine:9092
spring.kafka.consumer.group-id=pagerank-group
spring.kafka.consumer.auto-offset-reset=earliest

pagerank.damping=0.85
pagerank.iterations=10