server.port=8081
spring.application.name=crawler-service

spring.kafka.bootstrap-servers=kafka-searchengine:9092

spring.kafka.consumer.group-id=crawler-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.data.redis.host=redis
spring.data.redis.port=6379