server.port=8080
spring.application.name=query-service

# Elasticsearch
spring.elasticsearch.uris=http://elasticsearch:9200

# Kafka (future use)
spring.kafka.bootstrap-servers=kafka-searchengine:9092

# Redis
spring.data.redis.host=redis
spring.data.redis.port=6379