server.port=8082
spring.application.name=indexer-service

spring.kafka.bootstrap-servers=kafka-searchengine:9092
spring.kafka.consumer.group-id=indexer-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.data.redis.host=redis
spring.data.redis.port=6379